from __future__ import annotations

import argparse
import json
from pathlib import Path

from .exp011_challenger import CapacityThreeProspectiveCharacter
from .runtime import Event


def learn_walk(a):
    a.step(Event(kind="neutral", context="morning", available_actions=("walk", "idle"), forced_action="walk"))
    a.step(Event(kind="outcome", context="morning", reward=1.0, forced_action="idle"))


def neutral(a, n, offset=0):
    for i in range(n):
        a.step(Event(kind="neutral", context=f"noise_{(i+offset)%7}", forced_action="idle"))


def habit_age_information_test():
    # Equal total event count and identical post-eligibility state. Only the historical
    # time of reinforcement differs. If canonical states converge exactly, the frozen
    # organism carries no explicit 'age since reward' variable once the eligibility
    # trace has expired.
    old = CapacityThreeProspectiveCharacter()
    fresh = CapacityThreeProspectiveCharacter()

    learn_walk(old)
    neutral(old, 1011)

    neutral(fresh, 1000)
    learn_walk(fresh)
    neutral(fresh, 11)

    return {
        "same_tick": old.tick == fresh.tick,
        "old_tick": old.tick,
        "fresh_tick": fresh.tick,
        "old_habit": old.habits.get(("morning", "walk")),
        "fresh_habit": fresh.habits.get(("morning", "walk")),
        "old_eligibility": [vars(x) for x in old.eligibility_records],
        "fresh_eligibility": [vars(x) for x in fresh.eligibility_records],
        "canonical_equal": old.serialize_persistent() == fresh.serialize_persistent(),
        "old_state": old.persistent_snapshot(),
        "fresh_state": fresh.persistent_snapshot(),
        "interpretation": "If equal, current frozen state cannot distinguish a much older reward from a recently reinforced habit after temporary eligibility evidence expires. However the existing habit scalar itself could, in principle, accumulate future weakening semantics without a new field.",
    }


def prospective_age_information_test():
    old = CapacityThreeProspectiveCharacter()
    fresh = CapacityThreeProspectiveCharacter()

    old.step(Event(kind="future_commitment", concern="remember", context="cue", forced_action="idle"))
    neutral(old, 1012)

    neutral(fresh, 1000)
    fresh.step(Event(kind="future_commitment", concern="remember", context="cue", forced_action="idle"))
    neutral(fresh, 12)

    return {
        "same_tick": old.tick == fresh.tick,
        "old_tick": old.tick,
        "fresh_tick": fresh.tick,
        "old_prospective": dict(old.prospective_commitments),
        "fresh_prospective": dict(fresh.prospective_commitments),
        "canonical_equal": old.serialize_persistent() == fresh.serialize_persistent(),
        "old_state": old.persistent_snapshot(),
        "fresh_state": fresh.persistent_snapshot(),
        "interpretation": "If equal, the existing identity+cue pair contains no age or last-refresh information. Age-sensitive prospective weakening cannot be computed retrospectively from the frozen state alone without changing update semantics or representation.",
    }


def rhythm_dynamics_test():
    def run(initial=None):
        a = CapacityThreeProspectiveCharacter()
        if initial:
            a.fatigue, a.affiliation, a.competence = initial
        actions=[a.step(Event(kind="neutral")) for _ in range(240)]
        tail=actions[-120:]
        periods=[p for p in range(1,31) if all(tail[i]==tail[i%p] for i in range(len(tail)))]
        return {"tail":tail,"periods":periods,"state":a.persistent_snapshot()}

    baseline=run()
    perturbations={
        "low":run((0.01,0.01,0.01)),
        "high":run((0.99,0.99,0.99)),
        "asymmetric":run((0.73,0.18,0.41)),
        "epsilon":run((0.250001,0.55,0.15)),
    }
    return {
        "baseline":baseline,
        "perturbations":perturbations,
        "all_eventually_periodic": all(bool(x["periods"]) for x in [baseline,*perturbations.values()]),
        "interpretation": "This failure does not initially look like missing episodic information. It is generated by deterministic need drift, deterministic action effects, deterministic scoring and deterministic tie-breaking under repeated neutral input. Perturbation checks test whether periodicity is an attractor rather than one special initial condition.",
    }


def run():
    habit=habit_age_information_test()
    prospective=prospective_age_information_test()
    rhythm=rhythm_dynamics_test()
    return {
        "frozen_basis":"v9.4_prospective_capacity_three / 5f949c6e882f780e1d4c07f0b6b3bccf330936aa",
        "habit_temporal_plasticity":habit,
        "prospective_temporal_plasticity":prospective,
        "deterministic_rhythm":rhythm,
        "selection_analysis":{
            "rewarded_routine_never_weakens":{
                "required_information_present_now":"habit identity/context/action and learned scalar value are present; explicit age-since-reinforcement is absent after eligibility expiry",
                "semantic_or_interaction_path_available":True,
                "reason":"the existing habit scalar can potentially change under carefully defined non-reinforcement/update semantics; a new record type is not yet earned"
            },
            "ancient_commitment_reactivates_unchanged":{
                "required_information_present_now":"identity+cue is present, but no scalar strength, age, refresh time, or other temporal state exists",
                "semantic_or_interaction_path_available":"uncertain",
                "reason":"an age-sensitive policy cannot retrospectively distinguish old from recent identical prospective records in the frozen state; this may require representational change unless an existing update interaction supplies a defensible signal"
            },
            "deterministic_rhythm":{
                "required_information_present_now":"current needs are present",
                "semantic_or_interaction_path_available":True,
                "reason":"periodicity is generated by deterministic dynamics and selection policy rather than an obvious missing historical fact"
            }
        },
        "recommended_next_for_preregistration":"rewarded_routine_never_weakens",
        "selection_reason":"It is the cleanest surviving continuity failure where the causal value already exists in an earned mechanism and a semantics-first hypothesis can be tested before introducing temporal metadata. Prospective aging has a stronger apparent information deficit, while deterministic rhythm is a distinct endogenous-dynamics class and should remain separate."
    }


def main():
    p=argparse.ArgumentParser(); p.add_argument("--json",type=Path); args=p.parse_args()
    r=run(); text=json.dumps(r,indent=2,sort_keys=True); print(text)
    if args.json:
        args.json.parent.mkdir(parents=True,exist_ok=True); args.json.write_text(text+"\n",encoding="utf-8")


if __name__=="__main__": main()
